ARG BASE_CONTAINER=openjdk:8
FROM ${BASE_CONTAINER}

ENV REFRESHED_AT=2019-05-01

LABEL Name="senzing/senzing-api-server-builder" \
      Maintainer="support@senzing.com" \
      Version="1.0.0"

# Build arguments.

ARG SENZING_G2_JAR_RELATIVE_PATHNAME=unknown
ARG SENZING_G2_JAR_VERSION=unknown

# Install packages via apt.

RUN apt-get update
RUN apt-get -y install \
      make \
      maven \
 && rm -rf /var/lib/apt/lists/*

# Copy the repository from the local host.

COPY . /git-repository

# Run the "make" command to create the artifacts.

WORKDIR /git-repository
RUN make \
	SENZING_G2_JAR_PATHNAME=/git-repository/${SENZING_G2_JAR_RELATIVE_PATHNAME} \
    SENZING_G2_JAR_VERSION=${SENZING_G2_JAR_VERSION} \
    package

# Runtime execution.

CMD /bin/bash
