ARG BASE_CONTAINER=openjdk:8
FROM ${BASE_CONTAINER}

ENV REFRESHED_AT=2019-03-21

LABEL Name="senzing/senzing-api-server-builder" \
      Version="1.0.0"

# Build arguments.

ARG SENZING_G2_JAR_RELATIVE_PATHNAME=target/g2.jar
ARG SENZING_G2_JAR_VERSION=1.5.0
ARG SENZING_API_SERVER_JAR_VERSION=1.5.1

# Install packages via apt.

RUN apt-get update
RUN apt-get -y install \
      make \
      maven \
 && rm -rf /var/lib/apt/lists/*

# Copy the repository from the local host.

COPY . /git-repository

# Run the "make" command to create the artifacts.

WORKDIR /git-repository

ENV SENZING_G2_JAR_PATHNAME=/git-repository/${SENZING_G2_JAR_RELATIVE_PATHNAME}
ENV SENZING_G2_JAR_VERSION=${SENZING_G2_JAR_VERSION}
ENV SENZING_API_SERVER_JAR_VERSION=${SENZING_API_SERVER_JAR_VERSION}

RUN make package

# At runtime, run the following:

CMD /bin/bash
