name: Pull Request Test Java API Server Build on Debian

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  prBuildSenzingJavaApiServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Capture environment variables
        run: printenv
      - name: Check if there are conflicts when local merging master
        id: local_merge_master
        run: git merge origin/master
      - name: Update submodules
        id: update_submodules
        run: git submodule update --init --recursive
      - name: Build Java API Server
        id: build_java_api_server
        run: make docker-build
      - name: Creating log folder
        run: mkdir -p tmp/log
      - name: Persisting Variables
        id: persisting_log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build_info
          path: tmp/log/build_info.json
  logPrBuildSenzingJavaApiServer:
    needs: prBuildSenzingJavaApiServer
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Get Build Job Info From FIle
        uses: actions/download-artifact@v2
        with:
          name: build_info
      - name: Set Variables With Build Info
        id: job_info
        run: |
          curl -v -L -u runner:${{ secrets.GITHUB_TOKEN }} -o job_info.json https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${{ github.run_id }}/jobs
          echo ::set-output name=log_url::$(cat job_info.json | jq --raw-output '.jobs | .[0] | .url')
          echo ::set-output name=html_url::$(cat job_info.json | jq --raw-output '.jobs | .[0] | .html_url')
          echo ::set-output name=status::$(cat job_info.json | jq --raw-output '.jobs | .[0] | .conclusion')
          echo ::set-output name=g2_version::$(cat build_info/build_info.json | jq --raw-output '.g2_version')
          echo ::set-output name=branch_name::$(echo ${GITHUB_REF##*/})
      - name: Generate log file
        run: curl -v -L -u runner:${{ secrets.GITHUB_TOKEN }} -o build_logs.txt ${{ steps.job_info.outputs.log_url }}/logs
      - name: Slack Notification
        id: slack_notification
        uses: senzing-factory/git-action-slack-notification@1.0.0
        if: contains(steps.job_info.outputs.status, 'failure')
        env:
          SLACK_CHANNEL: production-build-failures
          SLACK_COLOR: '#3278BD'
          SLACK_TITLE: Senzing API server failed to build on commit sha ${{ github.sha }} using G2 Version ${{ steps.job_info.outputs.g2_version }}
          SLACK_MESSAGE: |
            OS: senzing/base-image-debian:1.0.3
            Senzing RPM version: ${{ steps.job_info.outputs.g2_version }}
            DEB URL: https://senzing-staging-apt.s3.amazonaws.com/senzingstagingrepo_1.0.0-1_amd64.deb
            Branch Name: ${{ steps.job_info.outputs.branch_name }}
            The commit SHA is: ${{ github.sha }}
            Git Actions Log URL: ${{ steps.job_info.outputs.html_url }}
          SLACK_USERNAME: senzing-api-server
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATION }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_ACTION: ${{ github.action }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
      - name: Persisting log
        id: persisting_log
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: workflow_log
          path: build_logs.txt
