name: docker push containers to dockerhub

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions: {}

jobs:
  docker-push-containers-to-dockerhub:
    outputs:
      status: ${{ job.status }}
    permissions:
      attestations: write
      contents: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: "0"
          persist-credentials: false
          submodules: recursive

      - name: get repo name
        id: repo-basename
        run: |
          echo "repo=$(basename ${{ github.repository }})" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: build docker image and push to DockerHub
        uses: senzing-factory/github-action-docker-buildx-build@v2
        with:
          image-repository: senzing/${{ steps.repo-basename.outputs.repo }}
          image-tag: ${{ github.ref_name }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          push: true
          sign-image: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}

  slack-notification:
    needs: [docker-push-containers-to-dockerhub]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.docker-push-containers-to-dockerhub.outputs.status) }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@v3
    with:
      job-status: ${{ needs.docker-push-containers-to-dockerhub.outputs.status }}
