name: docker push containers to dockerhub

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  docker-push-containers-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          submodules: recursive

      - name: get repo name
        id: repo-basename
        run: |
          echo "repo=$(basename ${{ github.repository }})" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: build docker image and push to DockerHub
        uses: senzing-factory/github-action-docker-buildx-build@v2
        with:
          image-repository: senzing/${{ steps.repo-basename.outputs.repo }}
          image-tag: ${{ github.ref_name }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          push: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
